# Generated by Django 6.0.4 on 2026-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldupdate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
